######################################################################
# Automatically generated by qmake (2.01a) mar. 17. avr. 15:29:51 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += CentauriPrime.cpp
