######################################################################
# Automatically generated by qmake (2.01a) mer. 11. avr. 14:09:01 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += console


# Input
SOURCES += Magicka.cpp
