######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 8 23:09:21 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += String.h
SOURCES += AlienLanguage.cpp String.cpp
