######################################################################
# Automatically generated by qmake (2.01a) jeu. 12. avr. 16:21:41 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += console

# Input
SOURCES += CandySplitting.cpp
