######################################################################
# Automatically generated by qmake (2.01a) mar. 17. avr. 15:47:16 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += console

# Input
SOURCES += MusicCollection.cpp
