######################################################################
# Automatically generated by qmake (2.01a) jeu. 5. avr. 14:33:27 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += Qt.cpp
