######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 9 17:34:30 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += BotTrust.cpp
